version: "3.4"
services:
  backend:
    container_name: CARS-backend-dev
    restart: always
    depends_on:
      - mongodb-shard0
    environment:
      WAIT_HOSTS: mongo:27017
      NODE_ENV: "development"
      TZ: Asia/Bangkok
      ORIGIN: http(|s):\/\/localhost:5000
      DATABASE_CONNECTION: "mongodb://mongodb-sharded:27017/cars-kmutt"
      DATABASE_USERAME: root
      DATABASE_PASSWORD: kmuttC@Rs2020
      DATABASE_AUTH_SOURCE: admin
      JWT_SECRET_KEY: secretKeyJwtEiei
      JWT_EXPIRES: 3600s
      OPS_KEY: 'kmuttC@Rs2020.OpsKey'
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - "./backend/src:/src"
    logging:
      options:
        max-size: 50m
  frontend:
    container_name: CARS-frontend-dev
    restart: always
    environment:
      NODE_ENV: "development"
      REACT_APP_TIMEZONE: Asia/Bangkok
    build:
      context: ./frontend-tsx
      dockerfile: Dockerfile
      target: dev
      args:
        REACT_APP_BACKEND_ENDPOINT: "http://localhost:3000/api"
    ports:
      - "5000:5000"
    volumes:
      - "./frontend-tsx/src:/src"
    logging:
      options:
        max-size: 50m
  mongodb-sharded:
    image: "bitnami/mongodb-sharded:4.2"
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-sharded
      MONGODB_SHARDING_MODE: mongos
      MONGODB_CFG_PRIMARY_HOST: mongodb-cfg
      MONGODB_CFG_REPLICA_SET_NAME: cfgreplicaset
      MONGODB_REPLICA_SET_KEY: kmuttCARs
      MONGODB_ROOT_PASSWORD: kmuttC@Rs2020
      TZ: Asia/Bangkok
    ports:
      - "27017:27017"
  mongodb-shard0:
    image: "bitnami/mongodb-sharded:4.2"
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-shard0
      MONGODB_SHARDING_MODE: shardsvr
      MONGODB_MONGOS_HOST: mongodb-sharded
      MONGODB_ROOT_PASSWORD: kmuttC@Rs2020
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: kmuttCARs
      MONGODB_REPLICA_SET_NAME: shard0
      TZ: Asia/Bangkok
    volumes:
      - "shard0_data:/bitnami"
  mongodb-cfg:
    image: "bitnami/mongodb-sharded:4.2"
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-cfg
      MONGODB_SHARDING_MODE: configsvr
      MONGODB_ROOT_PASSWORD: kmuttC@Rs2020
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: kmuttCARs
      MONGODB_REPLICA_SET_NAME: cfgreplicaset
      TZ: Asia/Bangkok
    volumes:
      - "cfg_data:/bitnami"

volumes:
  shard0_data:
    driver: local
  cfg_data:
    driver: local
